// DEPRECATED: This route (/contractor/subscription) is no longer the live pricing page.
// The production pricing/subscription page is at /contractor/subscriptions (plural).
// This file exists only as a safety redirect for old bookmarks or stale links.
// DO NOT edit this file for pricing or subscription changes — edit /contractor/subscriptions/page.tsx instead.

import { redirect } from "next/navigation";

export default function DeprecatedSubscriptionPage() {
  redirect("/contractor/subscriptions");
}
