// Toronto Pinpoint SEO Data
// 52 Toronto neighbourhoods × 16 services = 832 programmatic SEO pages
// Targeting local search: "kitchen renovation North York", "plumber Danforth", etc.

export interface TorontoNeighbourhood {
  slug: string;
  name: string;
  district: string; // e.g. "North York", "Etobicoke", "Scarborough"
  postalPrefixes: string[];
  avgHome: string;
  population: string;
  description: string;
  renovationNotes: string;
  nearbyAreas: string[];
}

export interface TorontoService {
  slug: string;
  name: string;
  shortName: string;
  avgCostLow: string;
  avgCostHigh: string;
  description: string;
  keywords: string[];
}

export const TORONTO_NEIGHBOURHOODS: TorontoNeighbourhood[] = [
  // ─── North York ───────────────────────────────────────────────
  {
    slug: "north-york",
    name: "North York",
    district: "North York",
    postalPrefixes: ["M2", "M3", "M4N"],
    avgHome: "$1.0M",
    population: "650K",
    description: "North York is one of Toronto's most densely populated districts, home to Yonge Street's commercial corridor and thousands of mid-century detached homes and condos. The area spans Sheppard, Finch, and Wilson neighbourhoods.",
    renovationNotes: "Many 1960s–1980s bungalows and two-storey detacheds in need of kitchen and bathroom modernization. Basement apartments are popular and renovation demand is strong year-round.",
    nearbyAreas: ["Willowdale", "York Mills", "Don Mills", "Lawrence Park"],
  },
  {
    slug: "willowdale",
    name: "Willowdale",
    district: "North York",
    postalPrefixes: ["M2M", "M2N", "M2R"],
    avgHome: "$1.05M",
    population: "95K",
    description: "Willowdale is a high-demand North York neighbourhood near Yonge and Sheppard. Known for newer condos mixed with older detached homes, it attracts families investing heavily in renovation.",
    renovationNotes: "Condo unit renovations (kitchens, bathrooms) and older detached home upgrades are both common. Competitive contractor market with strong ROI on renovations.",
    nearbyAreas: ["North York", "Newtonbrook", "Bayview Village", "Lansing"],
  },
  {
    slug: "york-mills",
    name: "York Mills",
    district: "North York",
    postalPrefixes: ["M2P", "M3B"],
    avgHome: "$1.4M",
    population: "45K",
    description: "York Mills is a prestigious North York enclave with luxury homes along the Don Valley Parkway corridor. Renovation projects here are large-scale and premium-finishedd.",
    renovationNotes: "Large custom home renovations, high-end kitchen and bathroom projects are the norm. Contractors working here command premium rates for quality finishes.",
    nearbyAreas: ["Hoggs Hollow", "Bayview Village", "Don Mills", "Lawrence Park"],
  },
  {
    slug: "don-mills",
    name: "Don Mills",
    district: "North York",
    postalPrefixes: ["M3A", "M3B", "M3C"],
    avgHome: "$970K",
    population: "60K",
    description: "Don Mills is Canada's first planned suburb, developed in the 1950s. Its distinctive mid-century modern bungalows and townhomes are increasingly popular renovation candidates.",
    renovationNotes: "Mid-century homes benefit enormously from kitchen extensions, bathroom modernization, and open-concept conversions. Strong ROI in this Toronto proper location.",
    nearbyAreas: ["North York", "Flemingdon Park", "Thorncliffe Park", "York Mills"],
  },
  {
    slug: "lawrence-park",
    name: "Lawrence Park",
    district: "North York",
    postalPrefixes: ["M4N"],
    avgHome: "$1.6M",
    population: "18K",
    description: "Lawrence Park is one of Toronto's most affluent residential neighbourhoods, with stately homes built in the early 1900s. A rare enclave of historic Toronto architecture.",
    renovationNotes: "Heritage home renovations, large kitchen and addition projects, and whole-home restorations are typical. Premium contractors with heritage experience are in demand.",
    nearbyAreas: ["Bedford Park", "Forest Hill", "Leaside", "Mount Pleasant"],
  },
  {
    slug: "newtonbrook",
    name: "Newtonbrook",
    district: "North York",
    postalPrefixes: ["M2M", "M2R"],
    avgHome: "$920K",
    population: "55K",
    description: "Newtonbrook spans both sides of Yonge Street in North York's northern reaches. A mix of older detacheds and newer builds with consistent renovation activity.",
    renovationNotes: "Basement finishing and in-law suites are particularly popular here. Homeowners frequently upgrade dated 1970s–1980s kitchens and bathrooms.",
    nearbyAreas: ["Willowdale", "Lansing", "Bathurst Manor", "Jane and Finch"],
  },

  // ─── Scarborough ──────────────────────────────────────────────
  {
    slug: "scarborough",
    name: "Scarborough",
    district: "Scarborough",
    postalPrefixes: ["M1", "M1B", "M1C"],
    avgHome: "$920K",
    population: "630K",
    description: "Scarborough is Toronto's east-end powerhouse — a vast district with diverse housing from postwar bungalows to modern semis. Spanning from the Bluffs to Steeles, it's one of the GTA's most active renovation markets.",
    renovationNotes: "Older bungalows from the 1950s–1970s are prime renovation candidates. Basement apartments, kitchen upgrades, and bathroom renovations deliver strong returns here.",
    nearbyAreas: ["Agincourt", "Wexford", "Malvern", "Kennedy Park"],
  },
  {
    slug: "agincourt",
    name: "Agincourt",
    district: "Scarborough",
    postalPrefixes: ["M1S", "M1V", "M1W"],
    avgHome: "$880K",
    population: "75K",
    description: "Agincourt is Scarborough's busy mid-section — a culturally diverse area with strong real estate demand. Older bungalows and semis are upgraded regularly by homeowners.",
    renovationNotes: "Kitchen and bathroom renovations drive most activity. Basement finishing for rental income is a top priority for many homeowners in this area.",
    nearbyAreas: ["Scarborough", "Wexford", "Milliken", "Steeles"],
  },
  {
    slug: "wexford",
    name: "Wexford",
    district: "Scarborough",
    postalPrefixes: ["M1R", "M1T"],
    avgHome: "$860K",
    population: "42K",
    description: "Wexford is a tight-knit Scarborough community with a stock of 1950s–1960s bungalows on large lots. It sits near the 401 corridor and has excellent transit access.",
    renovationNotes: "Complete home gut renovations are common as buyers capitalize on large lots and affordable-relative-to-Toronto prices. Kitchen and basement projects are the most popular.",
    nearbyAreas: ["Agincourt", "Clairlea", "Scarborough Village", "Don Mills"],
  },
  {
    slug: "malvern",
    name: "Malvern",
    district: "Scarborough",
    postalPrefixes: ["M1B"],
    avgHome: "$840K",
    population: "58K",
    description: "Malvern is a large, family-oriented Scarborough neighbourhood in Toronto's northeast. Known for affordable housing and growing renovation demand as a new wave of homeowners invests in properties.",
    renovationNotes: "Flooring, painting, bathroom upgrades, and energy-efficient window replacements are the most requested services here. Contractors offer competitive rates in this area.",
    nearbyAreas: ["Scarborough", "Agincourt", "Morningside", "Steeles"],
  },

  // ─── Etobicoke ────────────────────────────────────────────────
  {
    slug: "etobicoke",
    name: "Etobicoke",
    district: "Etobicoke",
    postalPrefixes: ["M8", "M9"],
    avgHome: "$980K",
    population: "360K",
    description: "Etobicoke is Toronto's western district — home to sprawling mid-century bungalows and executive-class homes near the Humber River and Lake Ontario.",
    renovationNotes: "1960s–1970s bungalows are especially popular for full kitchen renovations, basement conversions, and addition projects. The large lots make additions feasible.",
    nearbyAreas: ["Mimico", "Long Branch", "Humber Bay", "Rexdale"],
  },
  {
    slug: "mimico",
    name: "Mimico",
    district: "Etobicoke",
    postalPrefixes: ["M8V", "M8W"],
    avgHome: "$950K",
    population: "35K",
    description: "Mimico is a lakeside Etobicoke community undergoing a renaissance. Located along Lake Shore Blvd, it mixes older homes with new condo development and has seen significant real estate investment.",
    renovationNotes: "Condo and older home renovations are both common. Outdoor decks and basement finishing have high demand given the waterfront lifestyle here.",
    nearbyAreas: ["Long Branch", "Humber Bay", "New Toronto", "Etobicoke"],
  },
  {
    slug: "humber-bay",
    name: "Humber Bay",
    district: "Etobicoke",
    postalPrefixes: ["M8X", "M8Y"],
    avgHome: "$975K",
    population: "28K",
    description: "Humber Bay is an upscale Etobicoke waterfront area popular with professionals and young families. Premium finishes are expected in renovation projects here.",
    renovationNotes: "High-end kitchen and bathroom renovations are the norm. Condo suite renovations are increasingly popular as the neighbourhood densifies.",
    nearbyAreas: ["Mimico", "Bloor West Village", "Kingsway", "Etobicoke"],
  },
  {
    slug: "rexdale",
    name: "Rexdale",
    district: "Etobicoke",
    postalPrefixes: ["M9V", "M9W"],
    avgHome: "$820K",
    population: "65K",
    description: "Rexdale is a growing Etobicoke neighbourhood with affordable housing close to Pearson Airport. Many long-term homeowners are now investing in upgrades.",
    renovationNotes: "Basic to mid-range renovations are most popular — bathroom updates, flooring replacement, roofing repairs, and painting. Competitive contractor pricing.",
    nearbyAreas: ["Etobicoke", "Weston", "Emery", "Humber Summit"],
  },

  // ─── East York / East Toronto ─────────────────────────────────
  {
    slug: "east-york",
    name: "East York",
    district: "East York",
    postalPrefixes: ["M4B", "M4C", "M4J"],
    avgHome: "$980K",
    population: "120K",
    description: "East York is one of Toronto's most sought-after residential areas, known for its tree-lined streets, brick semis, and strong sense of community.",
    renovationNotes: "Older semis and detacheds respond extremely well to kitchen and bathroom renovations. Basement suites for rental income are popular given land values.",
    nearbyAreas: ["Leslieville", "Danforth", "Leaside", "Scarborough"],
  },
  {
    slug: "leaside",
    name: "Leaside",
    district: "East York",
    postalPrefixes: ["M4G"],
    avgHome: "$1.35M",
    population: "25K",
    description: "Leaside is an exclusive Toronto neighbourhood with beautiful 1930s–1950s homes and strong school districts. Real estate here rarely dips and renovation ROI is excellent.",
    renovationNotes: "Full home restorations, kitchen extensions, bathroom gut renovations, and second-storey additions are all common. Buyers invest heavily before listing.",
    nearbyAreas: ["Rosedale", "Thorncliffe Park", "East York", "Davisville"],
  },
  {
    slug: "leslieville",
    name: "Leslieville",
    district: "East Toronto",
    postalPrefixes: ["M4M", "M4K", "M4L"],
    avgHome: "$1.0M",
    population: "30K",
    description: "Leslieville is Toronto's most hipster-chic east-end neighbourhood, packed with Victorian semis, trendy cafes, and strong community pride. Renovation activity is constant.",
    renovationNotes: "Victorian semi renovations, kitchen modernizations, and laneway house conversions are all popular here. Strong contractor network with experience in narrow homess.",
    nearbyAreas: ["The Beaches", "East York", "Danforth", "Riverside"],
  },
  {
    slug: "the-beaches",
    name: "The Beaches",
    district: "East Toronto",
    postalPrefixes: ["M4E", "M4L"],
    avgHome: "$1.2M",
    population: "22K",
    description: "The Beaches (Beach) is Toronto's lakeside gem — a neighbourhood of Victorian homes, excellent schools, and a walkable boardwalk. Real estate here commands a premium.",
    renovationNotes: "Quality finishes expected. Kitchen, bathroom, deck, and home addition projects are common. Older properties near the boardwalk are frequently fully renovated.",
    nearbyAreas: ["Leslieville", "East York", "Scarborough Bluffs", "Danforth"],
  },
  {
    slug: "danforth",
    name: "Danforth Village",
    district: "East Toronto",
    postalPrefixes: ["M4J", "M4K"],
    avgHome: "$950K",
    population: "35K",
    description: "Danforth Village (The Danforth) stretches along Danforth Avenue past Coxwell. A vibrant, walkable east-end community with strong real estate fundamentals.",
    renovationNotes: "Older semis and detacheds are popular for basement finishing, kitchen renovations, and bathroom upgrades. Strong rental demand makes investment renovations worthwhile.",
    nearbyAreas: ["East York", "Leslieville", "Riverdale", "Woodbine"],
  },
  {
    slug: "riverdale",
    name: "Riverdale",
    district: "East Toronto",
    postalPrefixes: ["M4J", "M4M"],
    avgHome: "$1.1M",
    population: "25K",
    description: "Riverdale spans both sides of the DVP, known for its Victorian row houses and artsy community. One of Toronto's most desirable east-end neighbourhoods.",
    renovationNotes: "Heritage row house renovations, kitchen gut jobs, and bathroom modernizations are the most common projects. Permits may be required for exterior changes on historical properties.",
    nearbyAreas: ["Leslieville", "Corktown", "Greenwood Coxwell", "East York"],
  },

  // ─── Downtown / Central Toronto ───────────────────────────────
  {
    slug: "corktown",
    name: "Corktown",
    district: "Downtown East",
    postalPrefixes: ["M5A"],
    avgHome: "$900K",
    population: "12K",
    description: "Corktown is one of Toronto's oldest neighbourhoods, now a trendy condo and loft district east of the downtown core. Its proximity to the Financial District makes it attractive for professionals.",
    renovationNotes: "Condo unit renovations are the dominant project type. Older heritage buildings being converted to lofts require specialized contractors.",
    nearbyAreas: ["St. Lawrence", "Distillery District", "Regent Park", "Leslieville"],
  },
  {
    slug: "king-west",
    name: "King West",
    district: "Downtown West",
    postalPrefixes: ["M5V"],
    avgHome: "$850K",
    population: "20K",
    description: "King West is Toronto's trendiest urban neighbourhood — the heart of the city's condo explosion. Hundreds of development projects and renovation jobs annually.",
    renovationNotes: "Condo unit renovations (kitchens, bathrooms, flooring, painting) are overwhelmingly the primary job type. High turnover means constant renovation demand.",
    nearbyAreas: ["Liberty Village", "Parkdale", "Queen West", "Entertainment District"],
  },
  {
    slug: "queen-west",
    name: "Queen West",
    district: "Downtown West",
    postalPrefixes: ["M6J", "M6K"],
    avgHome: "$870K",
    population: "22K",
    description: "Queen West and West Queen West are the creative heart of Toronto. Victorian row houses and converted commercial buildings define the streetscape.",
    renovationNotes: "Victorian homes, semi-detacheds, and commercial-to-residential conversions are the primary project types. Creative renovations that preserve character are valued.",
    nearbyAreas: ["Parkdale", "Trinity Bellwoods", "Kensington", "Ossington"],
  },
  {
    slug: "parkdale",
    name: "Parkdale",
    district: "Downtown West",
    postalPrefixes: ["M6K"],
    avgHome: "$900K",
    population: "30K",
    description: "Parkdale is a rapidly gentrifying west-end neighbourhood. Victorian detacheds and semis are being snapped up by buyers who renovate to unlock value.",
    renovationNotes: "Whole-home renovations on Victorian properties are the most common project type. Kitchens, bathrooms, and structural work (knocking down walls for open plan) are high demand.",
    nearbyAreas: ["High Park", "Queen West", "Roncesvalles", "Liberty Village"],
  },
  {
    slug: "liberty-village",
    name: "Liberty Village",
    district: "Downtown West",
    postalPrefixes: ["M6K"],
    avgHome: "$780K",
    population: "15K",
    description: "Liberty Village is Toronto's tech-hub neighbourhood, dominated by condo towers and converted industrial lofts. A young professional demographic drives renovation spending.",
    renovationNotes: "Condo suite renovations (open-concept kitchen, bathroom tile upgrades, flooring, painting) are core project types. Commercial-space renovations also happen here.",
    nearbyAreas: ["King West", "Parkdale", "Exhibition Place", "Niagara"],
  },
  {
    slug: "annex",
    name: "The Annex",
    district: "Midtown West",
    postalPrefixes: ["M5R"],
    avgHome: "$1.1M",
    population: "30K",
    description: "The Annex is one of Toronto's most historic and intellectually vibrant neighbourhoods, surrounding U of T. Grand Victorian houses mixed with student rental properties.",
    renovationNotes: "Large Victorian home renovations, heritage-aware work, and multi-unit conversions are all common. Permits and heritage constraints should be checked before starting.",
    nearbyAreas: ["Yorkville", "Seaton Village", "Rosedale", "Davisville"],
  },
  {
    slug: "yorkville",
    name: "Yorkville",
    district: "Midtown",
    postalPrefixes: ["M4W", "M5R"],
    avgHome: "$1.5M",
    population: "12K",
    description: "Yorkville is Toronto's most luxurious neighbourhood — packed with high-end boutiques, five-star hotels, and multi-million-dollar condos. Renovation projects demand premium contractors.",
    renovationNotes: "Ultra-high-end condo renovations and luxury house restorations. Premium materials, custom cabinetry, and high-end finishing trades are standard here.",
    nearbyAreas: ["The Annex", "Rosedale", "Bloor-Yonge", "Summerhill"],
  },
  {
    slug: "rosedale",
    name: "Rosedale",
    district: "Midtown",
    postalPrefixes: ["M4W"],
    avgHome: "$2.2M",
    population: "10K",
    description: "Rosedale is Toronto's most storied luxury neighbourhood, home to heritage mansions and estates. Renovation projects here are large-scale and premium.",
    renovationNotes: "Full heritage home restorations, high-end kitchen and bath renovations, landscaping and additions. Multi-million dollar renovation budgets are common in this area.",
    nearbyAreas: ["Yorkville", "Moore Park", "Leaside", "Forest Hill"],
  },
  {
    slug: "forest-hill",
    name: "Forest Hill",
    district: "Midtown North",
    postalPrefixes: ["M5P"],
    avgHome: "$2.0M",
    population: "14K",
    description: "Forest Hill is one of Toronto's elite residential enclaves with mansion-lined streets and prestigious private schools. Renovation demand is consistently high.",
    renovationNotes: "Complete home renovations, premium kitchen and bath projects, landscaping, pool installations, and large-scale restoration. Top-tier contractors work here exclusively.",
    nearbyAreas: ["Lawrence Park", "Upper Canada College area", "Cedarvale", "Annex"],
  },
  {
    slug: "davisville",
    name: "Davisville Village",
    district: "Midtown",
    postalPrefixes: ["M4S"],
    avgHome: "$1.15M",
    population: "22K",
    description: "Davisville Village is a highly livable midtown Toronto neighbourhood beloved by young families. Its 1920s–1940s homes are consistently undergoing renovation.",
    renovationNotes: "Classic Toronto brick semis are popular for kitchen and bath renovations, second-storey additions, and open-concept conversions. Strong ROI in this in-demand market.",
    nearbyAreas: ["Mount Pleasant", "Moore Park", "Leaside", "Yonge-Eglinton"],
  },
  {
    slug: "mount-pleasant",
    name: "Mount Pleasant",
    district: "Midtown",
    postalPrefixes: ["M4P", "M4S"],
    avgHome: "$1.3M",
    population: "18K",
    description: "Mount Pleasant Village straddles the Midtown/East York boundary, known for boutique shopping and beautiful residential streets. One of the most desirable family neighbourhoods in Toronto.",
    renovationNotes: "Full home renovations, second-storey additions, and premium kitchen/bath projects are typical. Quick renovation ROI thanks to very strong resale demand.",
    nearbyAreas: ["Davisville", "Leaside", "Moore Park", "Rosedale"],
  },

  // ─── West Toronto ─────────────────────────────────────────────
  {
    slug: "high-park",
    name: "High Park",
    district: "West End",
    postalPrefixes: ["M6R", "M6S"],
    avgHome: "$1.1M",
    population: "32K",
    description: "High Park is Toronto's west-end gem — a neighbourhood of leafy streets, gorgeous Victorian homes, and proximity to the city's largest park. Extremely desirable for families.",
    renovationNotes: "Victorian and Edwardian homes frequently undergo full renovation to restore and modernize. Kitchens, bathrooms, and structural work are all in high demand.",
    nearbyAreas: ["Roncesvalles", "Parkdale", "Bloor West Village", "Swansea"],
  },
  {
    slug: "roncesvalles",
    name: "Roncesvalles",
    district: "West End",
    postalPrefixes: ["M6R"],
    avgHome: "$1.05M",
    population: "18K",
    description: "Roncesvalles (\"Roncy\") is a beloved west-end neighbourhood with a strong Polish heritage and vibrant cafe culture. Victorian homes line the streets and renovations happen constantly.",
    renovationNotes: "Victorian homes on narrow lots — experienced contractors are needed. Kitchen, bath, and basement finishing are the top jobs. Some heritage constraints on exteriors.",
    nearbyAreas: ["High Park", "Parkdale", "Bloor West Village", "Sunnyside"],
  },
  {
    slug: "bloor-west",
    name: "Bloor West Village",
    district: "West End",
    postalPrefixes: ["M6S"],
    avgHome: "$1.2M",
    population: "20K",
    description: "Bloor West Village is one of Toronto's most charming neighbourhood commercial strips, surrounded by beautiful residential streets. A top destination for families.",
    renovationNotes: "Large detached and semi-detached homes are regularly upgraded. Second-storey additions, full kitchen renovations, and backyard projects are all popular here.",
    nearbyAreas: ["High Park", "Roncesvalles", "Swansea", "Kingsway"],
  },
  {
    slug: "swansea",
    name: "Swansea",
    district: "West End",
    postalPrefixes: ["M6S"],
    avgHome: "$1.3M",
    population: "12K",
    description: "Swansea is an exclusive west-end enclave next to High Park and the Humber River. Premium homes sit on large lots with strong renovation activity.",
    renovationNotes: "Large-scale home renovations including additions and full interior gut jobs. Premium finishes expected. Landscaping and deck projects also common given large yards.",
    nearbyAreas: ["Bloor West Village", "High Park", "Kingsway", "Humber Bay"],
  },
  {
    slug: "kensington",
    name: "Kensington Market",
    district: "Downtown West",
    postalPrefixes: ["M5T"],
    avgHome: "$850K",
    population: "15K",
    description: "Kensington Market is one of Toronto's most eclectic and historic neighbourhoods. Victorian row houses and converted commercial spaces create a unique renovation landscape.",
    renovationNotes: "Heritage constraints apply on many properties. Contractors experienced with Victorian and Edwardian homes are sought after. Kitchens and bathrooms are the most common upgrades.",
    nearbyAreas: ["Chinatown", "Annex", "Trinity Bellwoods", "Queen West"],
  },
  {
    slug: "dovercourt",
    name: "Dovercourt–Wallace Emerson",
    district: "West Central",
    postalPrefixes: ["M6H"],
    avgHome: "$950K",
    population: "28K",
    description: "The Dovercourt area spans Bloor and Dufferin, home to renovated Victorian houses and a diverse, creative community. Real estate investment has surged here.",
    renovationNotes: "Victorian semis and detacheds are the most common renovation type. Open-concept kitchen conversions, basement finishing, and bathroom updates are popular.",
    nearbyAreas: ["Bloorcourt", "Junction", "Dufferin Grove", "Ossington"],
  },

  // ─── Midtown / Yonge St. Corridor ─────────────────────────────
  {
    slug: "yonge-eglinton",
    name: "Yonge-Eglinton",
    district: "Midtown",
    postalPrefixes: ["M4P", "M4R"],
    avgHome: "$1.1M",
    population: "40K",
    description: "Yonge-Eglinton is Midtown Toronto's commercial and residential hub — one of the city's most transit-connected and walkable neighbourhoods. High condo and house renovation activity.",
    renovationNotes: "Condo renovations and older house upgrades are both common. The arrival of the Eglinton Crosstown LRT has spurred renovation investment in the area.",
    nearbyAreas: ["Davisville", "Mount Pleasant", "Forest Hill", "Lawrence"],
  },
  {
    slug: "st-clair-west",
    name: "St. Clair West",
    district: "Midtown West",
    postalPrefixes: ["M6C", "M6E"],
    avgHome: "$980K",
    population: "30K",
    description: "St. Clair West is a vibrant midtown neighbourhood stretching from Oakwood to Dufferin. Known for Italian heritage and increasingly popular with young families.",
    renovationNotes: "Older Italian-built brick homes from the 1940s–1960s are popular renovation targets. Kitchen and bathroom upgrades, and basement conversion are the top jobs.",
    nearbyAreas: ["Corso Italia", "Wychwood", "Forest Hill", "Cedarvale"],
  },
  {
    slug: "corso-italia",
    name: "Corso Italia",
    district: "West Central",
    postalPrefixes: ["M6B", "M6E"],
    avgHome: "$940K",
    population: "25K",
    description: "Corso Italia on St. Clair West is a proud Italian-Canadian neighbourhood with well-maintained homes and a strong sense of community. Renovation investment is consistent.",
    renovationNotes: "Solid brick homes from the 1950s–1970s are upgraded with modern kitchens, bathrooms, and HVAC systems. Italian craftsmanship traditions make quality renovations the standard.",
    nearbyAreas: ["St. Clair West", "Wychwood", "Earlscourt", "Davenport"],
  },

  // ─── Junction / West Central ──────────────────────────────────
  {
    slug: "junction",
    name: "The Junction",
    district: "West Central",
    postalPrefixes: ["M6N", "M6P"],
    avgHome: "$920K",
    population: "22K",
    description: "The Junction is one of Toronto's most energetic rejuvenating neighbourhoods — Victorian homes and converted commercial buildings are a renovator's playground.",
    renovationNotes: "Full home renovations of Victorian properties are the most common project type. Live-work combinations, basement apartments, and open-concept conversions are popular.",
    nearbyAreas: ["Dundas West", "High Park North", "Runnymede", "Weston Road"],
  },
  {
    slug: "bloorcourt",
    name: "Bloorcourt Village",
    district: "West Central",
    postalPrefixes: ["M6G", "M6H"],
    avgHome: "$950K",
    population: "22K",
    description: "Bloorcourt stretches along Bloor West between Dufferin and Lansdowne. A lively neighbourhood with decades-old Victorian properties rising in value.",
    renovationNotes: "Victorian and Edwardian semis and detacheds for kitchen, bath, and basement renovations. Roofing and masonry repairs are also common on older properties here.",
    nearbyAreas: ["Dovercourt", "Ossington", "Dufferin Grove", "Bloordale"],
  },

  // ─── Thorncliffe / Flemingdon ──────────────────────────────────
  {
    slug: "thorncliffe-park",
    name: "Thorncliffe Park",
    district: "East York/Leaside",
    postalPrefixes: ["M4H"],
    avgHome: "$750K",
    population: "35K",
    description: "Thorncliffe Park is a dense, multicultural Toronto neighbourhood near the Don Valley. Mostly apartment towers and older townhouses with a growing renovation market.",
    renovationNotes: "Townhouse and low-rise unit renovations are the most common jobs. Kitchen and bathroom upgrades at mid-range price points. Growing contractor presence in the area.",
    nearbyAreas: ["Flemingdon Park", "Leaside", "East York", "Don Mills"],
  },
  {
    slug: "flemingdon-park",
    name: "Flemingdon Park",
    district: "North York/Scarborough",
    postalPrefixes: ["M3C"],
    avgHome: "$730K",
    population: "30K",
    description: "Flemingdon Park is a large apartment-tower neighbourhood adjacent to Don Mills. Investment in unit renovations is growing as the area attracts new residents.",
    renovationNotes: "Apartment and condo unit renovations: kitchen and bathroom upgrades, flooring, painting. Lower renovation cost range makes it accessible for first-time investors.",
    nearbyAreas: ["Don Mills", "Thorncliffe Park", "Scarborough", "North York"],
  },

  // ─── Weston / Jane-Finch ──────────────────────────────────────
  {
    slug: "weston",
    name: "Weston",
    district: "North York/Etobicoke border",
    postalPrefixes: ["M9M", "M9N"],
    avgHome: "$820K",
    population: "20K",
    description: "Weston is a west-side Toronto neighbourhood undergoing significant renewal, with small Victorian and post-war homes and community investment in upgrades.",
    renovationNotes: "Entry-level and mid-range renovations: kitchen and bathroom updates, roofing, energy upgrades. Good value for contractors and homeowners alike.",
    nearbyAreas: ["Emery", "Rexdale", "Humber Summit", "Mount Dennis"],
  },
  {
    slug: "jane-finch",
    name: "Jane & Finch",
    district: "North York",
    postalPrefixes: ["M3L", "M3M", "M3N"],
    avgHome: "$760K",
    population: "85K",
    description: "Jane and Finch is one of Toronto's largest and most vibrant communities. With significant community investment and a large housing stock, renovation activity is growing.",
    renovationNotes: "Mid-range home and unit renovations. Basement finishing for additional income is popular. Roofing, windows, and energy upgrades are common exterior projects.",
    nearbyAreas: ["North York", "Weston", "Newtonbrook", "Downsview"],
  },

  // ─── Steeles / Downsview ──────────────────────────────────────
  {
    slug: "downsview",
    name: "Downsview",
    district: "North York",
    postalPrefixes: ["M3K", "M3L"],
    avgHome: "$870K",
    population: "45K",
    description: "Downsview is a north-central Toronto neighbourhood undergoing transformation near the former Bombardier site. A mix of older detacheds and new development.",
    renovationNotes: "Older bungalows and semis are popular renovation projects. Basement suites, kitchen modernizations, and roofing are the most common jobs.",
    nearbyAreas: ["Jane-Finch", "Bathurst Manor", "North York", "Sheppard West"],
  },
  {
    slug: "bathurst-manor",
    name: "Bathurst Manor",
    district: "North York",
    postalPrefixes: ["M2R", "M3H"],
    avgHome: "$950K",
    population: "30K",
    description: "Bathurst Manor is an established North York neighbourhood north of Wilson Avenue. Large lot bungalows built in the 1950s–1970s are a favourite for renovation flips and upgrades.",
    renovationNotes: "Mid-century bungalow renovations: open-concept kitchen expansions, second-floor additions, and basement finishing are all very common. Strong ROI in this location.",
    nearbyAreas: ["Wilson Heights", "Newtonbrook", "Downsview", "Lawrence"],
  },

  // ─── Birchcliff / East Scarborough ────────────────────────────
  {
    slug: "birchcliff",
    name: "Birchcliff",
    district: "Scarborough/East York border",
    postalPrefixes: ["M1N"],
    avgHome: "$940K",
    population: "18K",
    description: "Birchcliff Heights is a small, highly desirable community on the Scarborough Bluffs. Well-maintained postwar bungalows with an exceptionally strong real estate market.",
    renovationNotes: "Full kitchen and bathroom renovations are popular as buyers modernize classic bungalows. Deck and outdoor projects are also common given the scenic ravine access.",
    nearbyAreas: ["The Beaches", "Kingston Road corridor", "Cliffside", "East York"],
  },
  {
    slug: "clairlea",
    name: "Clairlea-Birchmount",
    district: "Scarborough",
    postalPrefixes: ["M1L", "M1N"],
    avgHome: "$900K",
    population: "28K",
    description: "Clairlea is a stable, family-oriented Scarborough neighbourhood. Solid 1950s–1960s detacheds are the dominant housing type, with consistent renovation activity.",
    renovationNotes: "Kitchen and bathroom upgrades, basement finishing, and roofing are the most common jobs. One of Scarborough's most active renovation markets.",
    nearbyAreas: ["East York", "Wexford", "Birchcliff", "Scarborough Village"],
  },

  // ─── Victoria Village / Lawrence East ─────────────────────────
  {
    slug: "victoria-village",
    name: "Victoria Village",
    district: "North York/Scarborough border",
    postalPrefixes: ["M4A"],
    avgHome: "$870K",
    population: "22K",
    description: "Victoria Village sits east of the DVP, a leafy enclave with affordable bungalows popular with first-time buyers. Renovation after purchase is extremely common.",
    renovationNotes: "First-time buyers frequently renovate immediately after purchasing. Kitchen and bathroom upgrades, and basement finishing are the most requested services.",
    nearbyAreas: ["Don Mills", "Flemingdon Park", "Scarborough", "East York"],
  },
  {
    slug: "st-lawrence",
    name: "St. Lawrence Market",
    district: "Old Town",
    postalPrefixes: ["M5E", "M5A"],
    avgHome: "$850K",
    population: "12K",
    description: "St. Lawrence is one of Toronto's oldest and most vibrant neighbourhoods, centred on the famous St. Lawrence Market. A mix of heritage lofts and modern condos.",
    renovationNotes: "Heritage loft and condo unit renovations. Custom kitchen remodels and bathroom upgrades in premium finishes. Heritage restrictions may apply on some buildings.",
    nearbyAreas: ["Corktown", "Distillery District", "Financial District", "Old Town"],
  },
  {
    slug: "seaton-village",
    name: "Seaton Village",
    district: "Midtown West",
    postalPrefixes: ["M6G"],
    avgHome: "$1.0M",
    population: "14K",
    description: "Seaton Village is a quiet pocket between The Annex and Bathurst. Home to beautiful Victorian and Edwardian houses on a human scale, it's a hidden gem of Toronto real estate.",
    renovationNotes: "Victorian and Edwardian home renovations, including kitchen gut jobs, bathroom renovations, and basement finishing. Strong community investment in home maintenance.",
    nearbyAreas: ["The Annex", "Christie Pits", "Bloorcourt", "Palmerston"],
  },
];

// Lookup map
export const NEIGHBOURHOOD_MAP: Record<string, TorontoNeighbourhood> = Object.fromEntries(
  TORONTO_NEIGHBOURHOODS.map((n) => [n.slug, n])
);

// ─── Services ─────────────────────────────────────────────────────────────────

export const TORONTO_SERVICES: TorontoService[] = [
  {
    slug: "kitchen-renovation",
    name: "Kitchen Renovation",
    shortName: "Kitchen",
    avgCostLow: "$15,000",
    avgCostHigh: "$65,000",
    description: "Full kitchen renovations including cabinets, countertops, appliances, plumbing, and electrical.",
    keywords: ["kitchen renovation", "kitchen remodel", "kitchen quote", "new kitchen", "kitchen contractor"],
  },
  {
    slug: "bathroom-renovation",
    name: "Bathroom Renovation",
    shortName: "Bathroom",
    avgCostLow: "$8,000",
    avgCostHigh: "$35,000",
    description: "Complete bathroom renovations — tile, vanity, fixtures, shower enclosures, and plumbing.",
    keywords: ["bathroom renovation", "bathroom remodel", "bathroom quote", "shower renovation", "bathroom contractor"],
  },
  {
    slug: "basement-finishing",
    name: "Basement Finishing",
    shortName: "Basement",
    avgCostLow: "$25,000",
    avgCostHigh: "$75,000",
    description: "Basement finishing and renovation — framing, insulation, drywall, flooring, bathroom, and suite creation.",
    keywords: ["basement finishing", "basement renovation", "basement quote", "basement suite", "finished basement"],
  },
  {
    slug: "home-renovation-quote",
    name: "Home Renovation Quote",
    shortName: "Home Renovation",
    avgCostLow: "$10,000",
    avgCostHigh: "$200,000",
    description: "Full home renovations and interior remodels, from single rooms to whole-home transformations.",
    keywords: ["home renovation quote", "renovation estimate", "house renovation", "home remodel", "renovation contractor"],
  },
  {
    slug: "roofing",
    name: "Roofing",
    shortName: "Roofing",
    avgCostLow: "$8,000",
    avgCostHigh: "$22,000",
    description: "Roof replacement and repair — shingles, flat roofs, skylights, ventilation, and gutters.",
    keywords: ["roofing contractor", "roof replacement", "roofing quote", "new roof", "roof repair"],
  },
  {
    slug: "flooring",
    name: "Flooring Installation",
    shortName: "Flooring",
    avgCostLow: "$3,000",
    avgCostHigh: "$15,000",
    description: "Hardwood, laminate, tile, vinyl plank, and carpet installation and refinishing.",
    keywords: ["flooring installation", "hardwood flooring", "flooring contractor", "flooring quote", "new floors"],
  },
  {
    slug: "painting",
    name: "Interior & Exterior Painting",
    shortName: "Painting",
    avgCostLow: "$2,500",
    avgCostHigh: "$8,000",
    description: "Full interior and exterior painting services — walls, ceilings, trim, and fencing.",
    keywords: ["painting contractor", "interior painting", "exterior painting", "house painter", "painting quote"],
  },
  {
    slug: "deck-building",
    name: "Deck Building",
    shortName: "Deck",
    avgCostLow: "$8,000",
    avgCostHigh: "$30,000",
    description: "Deck construction and replacement — wood, composite, PVC. Includes permits and railings.",
    keywords: ["deck building", "deck contractor", "new deck", "deck quote", "deck installation"],
  },
  {
    slug: "plumbing",
    name: "Plumbing",
    shortName: "Plumbing",
    avgCostLow: "$300",
    avgCostHigh: "$12,000",
    description: "Plumbing repairs and upgrades — pipe replacement, water heater, fixture installation, and drain work.",
    keywords: ["plumber", "plumbing contractor", "plumbing repair", "plumber near me", "plumbing quote"],
  },
  {
    slug: "electrical",
    name: "Electrical",
    shortName: "Electrical",
    avgCostLow: "$500",
    avgCostHigh: "$15,000",
    description: "Electrical panel upgrades, wiring, outlet installation, EV charger, and outdoor lighting.",
    keywords: ["electrician", "electrical contractor", "electrical repair", "electrician near me", "electrical quote"],
  },
  {
    slug: "hvac",
    name: "HVAC & Furnace",
    shortName: "HVAC",
    avgCostLow: "$3,000",
    avgCostHigh: "$18,000",
    description: "Furnace and AC replacement, ductwork installation, heat pump, and ventilation work.",
    keywords: ["HVAC contractor", "furnace replacement", "air conditioner", "heating cooling", "HVAC quote"],
  },
  {
    slug: "window-replacement",
    name: "Window Replacement",
    shortName: "Windows",
    avgCostLow: "$5,000",
    avgCostHigh: "$20,000",
    description: "Energy-efficient window replacement — casement, double-hung, egress, and skylights.",
    keywords: ["window replacement", "new windows", "window contractor", "window quote", "energy efficient windows"],
  },
  {
    slug: "home-addition",
    name: "Home Addition",
    shortName: "Addition",
    avgCostLow: "$80,000",
    avgCostHigh: "$250,000",
    description: "Second-storey additions, rear extensions, garage conversions, and sunroom additions.",
    keywords: ["home addition", "house addition", "second storey addition", "addition contractor", "home extension"],
  },
  {
    slug: "landscaping",
    name: "Landscaping",
    shortName: "Landscaping",
    avgCostLow: "$3,000",
    avgCostHigh: "$25,000",
    description: "Landscaping design and installation — patios, interlocking stone, planting, and retaining walls.",
    keywords: ["landscaping contractor", "landscape design", "interlocking stone", "landscaping quote", "patio"],
  },
  {
    slug: "handyman",
    name: "Handyman Services",
    shortName: "Handyman",
    avgCostLow: "$200",
    avgCostHigh: "$3,000",
    description: "General handyman services — drywall repair, fixtures, carpentry, assembly, and minor repairs.",
    keywords: ["handyman", "handyman services", "handyman near me", "home repair", "handyman quote"],
  },
  {
    slug: "general-contractor",
    name: "General Contractor",
    shortName: "General",
    avgCostLow: "$15,000",
    avgCostHigh: "$300,000",
    description: "General contracting for major renovations, full home projects, and new construction.",
    keywords: ["general contractor", "general contractor near me", "renovation contractor", "GC contractor", "contractor quote"],
  },
];

export const SERVICE_MAP: Record<string, TorontoService> = Object.fromEntries(
  TORONTO_SERVICES.map((s) => [s.slug, s])
);

// Generate all static route params: 52 × 16 = 832 pages
export function getTorontoPinpointParams() {
  const params: { neighbourhood: string; service: string }[] = [];
  for (const n of TORONTO_NEIGHBOURHOODS) {
    for (const s of TORONTO_SERVICES) {
      params.push({ neighbourhood: n.slug, service: s.slug });
    }
  }
  return params;
}
