'use client';

import { useState, useRef, useEffect } from 'react';
import { FileText, Download, Printer, Edit3, Check, Sparkles, Mic, MicOff } from 'lucide-react';
import Image from 'next/image';
import { useToast } from '@/components/ToastProvider';

export default function AIQuotePage() {
  const toast = useToast();
  const [loading, setLoading] = useState(false);
  const [generatedQuote, setGeneratedQuote] = useState('');
  const [editing, setEditing] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const recognitionRef = useRef<any>(null);
  
  // Form data
  const [formData, setFormData] = useState({
    projectType: '',
    description: '',
    location: '',
    timeline: '',
    budget: '',
    companyName: '',
    clientName: '',
    clientEmail: '',
    clientPhone: ''
  });

  // Initialize speech recognition
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
      if (SpeechRecognition) {
        recognitionRef.current = new SpeechRecognition();
        recognitionRef.current.continuous = true;
        recognitionRef.current.interimResults = true;
        
        recognitionRef.current.onresult = (event: any) => {
          let interimTranscript = '';
          let finalTranscript = '';
          
          for (let i = event.resultIndex; i < event.results.length; i++) {
            const transcript = event.results[i][0].transcript;
            if (event.results[i].isFinal) {
              finalTranscript += transcript + ' ';
            } else {
              interimTranscript += transcript;
            }
          }
          
          if (finalTranscript) {
            setFormData(prev => ({
              ...prev,
              description: prev.description + finalTranscript
            }));
          }
        };
        
        recognitionRef.current.onerror = (event: any) => {
          console.error('Speech recognition error:', event.error);
          setIsRecording(false);
          if (event.error === 'not-allowed') {
            toast.error('Microphone access denied. Please enable microphone permissions.');
          } else {
            toast.error('Voice input error. Please try again.');
          }
        };
        
        recognitionRef.current.onend = () => {
          setIsRecording(false);
        };
      }
    }
    
    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
    };
  }, [toast]);

  const toggleVoiceInput = () => {
    if (!recognitionRef.current) {
      toast.error('Voice input is not supported in your browser. Please use Chrome, Edge, or Safari.');
      return;
    }
    
    if (isRecording) {
      recognitionRef.current.stop();
      setIsRecording(false);
      toast.success('Voice input stopped');
    } else {
      recognitionRef.current.start();
      setIsRecording(true);
      toast.success('Voice input started - speak now!');
    }
  };

  const generateQuote = async () => {
    if (!formData.projectType || !formData.description || !formData.companyName) {
      toast.warning('Please fill in at least Project Type, Description, and Company Name');
      return;
    }

    setLoading(true);
    toast.info('Generating professional quote with AI...');
    
    try {
      const response = await fetch('/api/ai-quote/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData)
      });

      const data = await response.json();
      if (data.success) {
        setGeneratedQuote(data.quote);
        setEditing(false);
        toast.success('Quote generated successfully!');
      } else {
        toast.error(data.error || 'Failed to generate quote');
      }
    } catch (error) {
      console.error('Error:', error);
      toast.error('Failed to generate quote. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Professional Quote</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
              h1 { color: #991B1B; border-bottom: 3px solid #F97316; padding-bottom: 10px; }
              .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; text-align: center; font-size: 12px; color: #666; }
            </style>
          </head>
          <body>
            ${generatedQuote}
            <div class="footer">
              <p><strong>Generated by QuoteXbert</strong> - Professional Quote & Contract Platform</p>
              <p>www.quotexbert.com | Connecting Homeowners with Verified Contractors</p>
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([generatedQuote], { type: 'text/html' });
    element.href = URL.createObjectURL(file);
    element.download = `quote-${Date.now()}.html`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-rose-50">
      {/* Hero Section */}
      <div className="bg-gradient-to-r from-rose-700 via-rose-600 to-orange-600 text-white py-16">
        <div className="container mx-auto px-4">
          <div className="text-center max-w-4xl mx-auto">
            <div className="flex items-center justify-center gap-3 mb-4">
              <Sparkles className="w-12 h-12" />
              <FileText className="w-12 h-12" />
            </div>
            <h1 className="text-5xl md:text-6xl font-black mb-4">Free AI Quote Generator</h1>
            <p className="text-xl md:text-2xl text-rose-100">
              Generate professional, detailed quotes & contracts in seconds
            </p>
            <p className="text-base md:text-lg text-white/90 mt-3">
              100% Free • Fully Editable • Print or Download • Legal Format
            </p>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left: Input Form */}
          <div className="bg-white rounded-2xl shadow-2xl p-8 border-2 border-gray-100">
            <h2 className="text-3xl font-black text-gray-900 mb-6 flex items-center gap-3">
              <span>📋</span>
              <span>Project Details</span>
            </h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">
                  Project Type *
                </label>
                <select
                  value={formData.projectType}
                  onChange={(e) => setFormData({...formData, projectType: e.target.value})}
                  className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                >
                  <option value="">Select project type...</option>
                  <option value="Kitchen Renovation">Kitchen Renovation</option>
                  <option value="Bathroom Renovation">Bathroom Renovation</option>
                  <option value="Basement Finishing">Basement Finishing</option>
                  <option value="Painting">Painting</option>
                  <option value="Roofing">Roofing</option>
                  <option value="Flooring">Flooring</option>
                  <option value="Electrical Work">Electrical Work</option>
                  <option value="Plumbing">Plumbing</option>
                  <option value="Custom Project">Custom Project</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center justify-between">
                  <span>Project Description *</span>
                  <button
                    type="button"
                    onClick={toggleVoiceInput}
                    className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-semibold transition-all ${
                      isRecording 
                        ? 'bg-red-600 text-white animate-pulse shadow-lg' 
                        : 'bg-rose-100 text-rose-700 hover:bg-rose-200'
                    }`}
                    title={isRecording ? 'Stop voice input' : 'Start voice input'}
                  >
                    {isRecording ? (
                      <>
                        <MicOff className="w-4 h-4" />
                        <span>Stop</span>
                      </>
                    ) : (
                      <>
                        <Mic className="w-4 h-4" />
                        <span>Voice</span>
                      </>
                    )}
                  </button>
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({...formData, description: e.target.value})}
                  rows={4}
                  placeholder="E.g., Complete kitchen renovation including new cabinets, countertops, appliances... (Click Voice button to dictate)"
                  className={`w-full px-4 py-3 border-2 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200 ${
                    isRecording ? 'border-red-500 ring-2 ring-red-200' : 'border-gray-300'
                  }`}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2">
                    Location
                  </label>
                  <input
                    type="text"
                    value={formData.location}
                    onChange={(e) => setFormData({...formData, location: e.target.value})}
                    placeholder="City, Province"
                    className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                  />
                </div>

                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2">
                    Timeline
                  </label>
                  <input
                    type="text"
                    value={formData.timeline}
                    onChange={(e) => setFormData({...formData, timeline: e.target.value})}
                    placeholder="E.g., 2-4 weeks"
                    className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">
                  Budget Range
                </label>
                <input
                  type="text"
                  value={formData.budget}
                  onChange={(e) => setFormData({...formData, budget: e.target.value})}
                  placeholder="E.g., $10,000 - $15,000"
                  className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                />
              </div>

              <div className="border-t-2 border-gray-200 pt-6 mt-6">
                <h3 className="text-xl font-bold text-gray-900 mb-4">Company & Client Details</h3>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-bold text-gray-700 mb-2">
                      Your Company Name *
                    </label>
                    <input
                      type="text"
                      value={formData.companyName}
                      onChange={(e) => setFormData({...formData, companyName: e.target.value})}
                      placeholder="ABC Construction Ltd."
                      className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-bold text-gray-700 mb-2">
                      Client Name
                    </label>
                    <input
                      type="text"
                      value={formData.clientName}
                      onChange={(e) => setFormData({...formData, clientName: e.target.value})}
                      placeholder="John Smith"
                      className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                    />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-bold text-gray-700 mb-2">
                        Client Email
                      </label>
                      <input
                        type="email"
                        value={formData.clientEmail}
                        onChange={(e) => setFormData({...formData, clientEmail: e.target.value})}
                        placeholder="client@email.com"
                        className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-bold text-gray-700 mb-2">
                        Client Phone
                      </label>
                      <input
                        type="tel"
                        value={formData.clientPhone}
                        onChange={(e) => setFormData({...formData, clientPhone: e.target.value})}
                        placeholder="(416) 555-1234"
                        className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <button
                onClick={generateQuote}
                disabled={loading}
                className="w-full bg-gradient-to-r from-rose-700 to-orange-600 text-white font-bold py-4 px-6 rounded-xl shadow-lg hover:shadow-2xl disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105 transition-all flex items-center justify-center gap-3"
              >
                {loading ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
                    <span>Generating Professional Quote...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    <span>Generate Quote with AI</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Right: Preview/Output */}
          <div className="bg-white rounded-2xl shadow-2xl border-2 border-gray-100 overflow-hidden">
            {!generatedQuote ? (
              <div className="h-full flex items-center justify-center p-12 bg-gradient-to-br from-rose-50 to-orange-50">
                <div className="text-center">
                  <FileText className="w-24 h-24 text-gray-300 mx-auto mb-4" />
                  <h3 className="text-2xl font-bold text-gray-600 mb-2">Your Quote Will Appear Here</h3>
                  <p className="text-gray-500">Fill in the form and click "Generate Quote with AI"</p>
                </div>
              </div>
            ) : (
              <>
                {/* Action Buttons */}
                <div className="bg-gradient-to-r from-gray-50 to-white border-b-2 border-gray-200 p-4 flex flex-wrap gap-3 justify-between items-center">
                  <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
                    <Check className="w-6 h-6 text-green-600" />
                    <span>Quote Generated</span>
                  </h2>
                  <div className="flex gap-2">
                    <button
                      onClick={() => setEditing(!editing)}
                      className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-semibold"
                    >
                      <Edit3 className="w-4 h-4" />
                      {editing ? 'Preview' : 'Edit'}
                    </button>
                    <button
                      onClick={handlePrint}
                      className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-semibold"
                    >
                      <Printer className="w-4 h-4" />
                      Print
                    </button>
                    <button
                      onClick={handleDownload}
                      className="flex items-center gap-2 px-4 py-2 bg-rose-600 text-white rounded-lg hover:bg-rose-700 font-semibold"
                    >
                      <Download className="w-4 h-4" />
                      Download
                    </button>
                  </div>
                </div>

                {/* Quote Content */}
                <div className="p-8 max-h-[800px] overflow-y-auto">
                  {editing ? (
                    <textarea
                      value={generatedQuote}
                      onChange={(e) => setGeneratedQuote(e.target.value)}
                      className="w-full h-[700px] p-4 border-2 border-gray-300 rounded-xl font-mono text-sm focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                    />
                  ) : (
                    <div 
                      className="prose prose-lg max-w-none"
                      dangerouslySetInnerHTML={{ __html: generatedQuote }}
                    />
                  )}

                  {/* QuoteXbert Stamp */}
                  <div className="mt-8 pt-6 border-t-2 border-gray-200 text-center">
                    <div className="inline-block bg-gradient-to-r from-rose-700 to-orange-600 text-white px-6 py-3 rounded-xl shadow-lg">
                      <div className="flex items-center gap-3">
                        <Check className="w-6 h-6" />
                        <div className="text-left">
                          <div className="font-black text-lg">QuoteXbert Approved</div>
                          <div className="text-xs text-rose-100">Professional Contract Platform</div>
                        </div>
                      </div>
                    </div>
                    <p className="text-sm text-gray-600 mt-4">
                      Generated by QuoteXbert • www.quotexbert.com
                    </p>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>

        {/* Benefits Section */}
        <div className="mt-16 bg-white rounded-2xl shadow-2xl p-8 md:p-12 border-2 border-gray-100">
          <h2 className="text-3xl font-black text-gray-900 mb-8 text-center">Why Use QuoteXbert AI Quote Generator?</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="text-5xl mb-4">⚡</div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Instant Generation</h3>
              <p className="text-gray-600">Professional quotes in seconds, not hours</p>
            </div>
            <div className="text-center">
              <div className="text-5xl mb-4">🎯</div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">100% Free</h3>
              <p className="text-gray-600">No hidden fees, no credit card required</p>
            </div>
            <div className="text-center">
              <div className="text-5xl mb-4">⚖️</div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Legal Format</h3>
              <p className="text-gray-600">Professional contract structure included</p>
            </div>
            <div className="text-center">
              <div className="text-5xl mb-4">✏️</div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Fully Editable</h3>
              <p className="text-gray-600">Customize every detail to match your needs</p>
            </div>
            <div className="text-center">
              <div className="text-5xl mb-4">🖨️</div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Print & Download</h3>
              <p className="text-gray-600">Export to PDF or print directly</p>
            </div>
            <div className="text-center">
              <div className="text-5xl mb-4">✅</div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">QuoteXbert Branded</h3>
              <p className="text-gray-600">Professional stamp of approval</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
